Experiment_name: st-gcn-pp
base_lr: 0.1
batch_size: 64
eval_interval: 1
feeder: feeder.feeder.Feeder
label_smoothing: 0
model: model.stgcn_pp.stgcn_pp.Model
model_args:
  gcn_adaptive: init
  gcn_with_res: true
  graph: graph.graph.Graph
  graph_args:
    layout: wlasl-49-nla
    mode: spatial
  in_channels: 3
  num_class: 2000
  tcn_type: mstcn
model_saved_dir: /kaggle/working/output/save_models
nesterov: true
num_epoch: 100
num_worker: 2
optimizer: SGD
phase: train
print_log: true
save_interval: 20
show_topk:
- 1
start_epoch: 0
t_max: 100
test_batch_size: 64
test_feeder_args:
  data_path: /kaggle/input/skeleton-49-rtm-l-384-288/skeleton-49-rtm-l-384-288/test_data_joint.npy
  label_path: /kaggle/input/skeleton-49-rtm-l-384-288/skeleton-49-rtm-l-384-288/test_label.pkl
  normalization: true
  random_mirror: false
  window_size: 60
train_feeder_args:
  data_path: /kaggle/input/skeleton-49-rtm-l-384-288/skeleton-49-rtm-l-384-288/train_data_joint.npy
  is_vector: false
  label_path: /kaggle/input/skeleton-49-rtm-l-384-288/skeleton-49-rtm-l-384-288/train_label.pkl
  max_xy: 256
  normalization: true
  random_choose: true
  random_mirror: true
  random_mirror_p: 0.5
  random_move: true
  random_shift: true
  window_size: 80
val_feeder_args:
  data_path: /kaggle/input/skeleton-49-rtm-l-384-288/skeleton-49-rtm-l-384-288/val_data_joint.npy
  label_path: /kaggle/input/skeleton-49-rtm-l-384-288/skeleton-49-rtm-l-384-288/val_label.pkl
  normalization: true
  random_mirror: false
  window_size: 60
weight_decay: 0.0005
weights: 0
work_dir: /kaggle/working/output/work_dir
